### ISSUE TITLE
Compilation warnings with more recent versions of elixir (`Application.get_env/3 is discouraged`,  `use Bitwise is deprecated`)

### ISSUE THREAD

**Issue by markmark206** [railsmechanic/nanoid#15]
Thank you for this neat package, it's super-useful.

I have been seeing warnings while compiling my applications that use nanoid, using a recent version of Elixir (this is running on Elixir 1.15.0 / OTP 26.0.1, but I have seen this with earlier versions as well):

```
$ mix compile
...
==> nanoid
Compiling 4 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
Warning:   lib/nanoid/configuration.ex:8: Nanoid.Configuration (module)

warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
Warning:   lib/nanoid/configuration.ex:9: Nanoid.Configuration (module)

warning: use Bitwise is deprecated. import Bitwise instead
Warning:   lib/nanoid/secure.ex:6: Nanoid.Secure (module)

Generated nanoid app
...
```

Thank you!

**Comment by railsmechanic** [comment]
Hi, thank you for this information. I published version 2.1.0 which requires elixir `~> 1.12` now and where the code is updated to compile without this warnings.
