### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [railsmechanic/nanoid#4]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [x] Replace `~` to `-` in default alphabet
- [x] Add `non-secure` fast generator
- [ ] Async API?

**Comment by railsmechanic** [comment]
Many thanks for your notice. I really overlooked it. I'm working on a version 2.0 👍

**Comment by railsmechanic** [comment]
Updated this port of nanoid to version 2.0. It replaces `~` with `-`and adds a `non-secure` generator.
But I decided not to add an async API, because it's really simple with Elixir to execute "work" (e.g. generating tokens) in an async manner.

```elixir
# Async example
task = Task.async(&Nanoid.generate/0)
IO.puts("Do some other work")
nanoid_token = Task.await(task)
```
